[tox]
envlist=py39,pillow10.x,flake8

[testenv]
usedevelop = True
extras =
    pdf
    rst
    testing
deps =
    pillow10.x: Pillow<11.0.0

passenv =
    ALL_TESTS
commands =
    nosetests

[testenv:flake8]
description =
    Run style checks.
extras =
    testing
commands =
    flake8 src
